version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  error:
    format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"
  file:
    format: "%(asctime)s - %(filename)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  warning_file_handler:
    class: logging.StreamHandler
    level: WARNING
    formatter: standard
    stream: ext://sys.stdout

  error_file_handler:
    class: logging.StreamHandler
    level: ERROR
    formatter: standard
    stream: ext://sys.stdout

loggers:
  common:
    level: INFO
    handlers: [console]
    # just output one time
    propagate: False
root:
  level: NOTSET
  handlers: [console]
  propagate: false
